// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NewCarRental.Infrastructure.Contexts;

#nullable disable

namespace NewCarRental.Infrastructure.Migrations
{
    [DbContext(typeof(CarRentalDbContext))]
    partial class CarRentalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NewCarRental.Domain.Entities.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PublishedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("BlogId")
                        .HasName("PK__Blog__54379E30930C48EE");

                    b.HasIndex(new[] { "AuthorId" }, "IX_Blog_AuthorId");

                    b.ToTable("Blog", (string)null);
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<int>("BaseLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CarName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int?>("DistanceTraveled")
                        .HasColumnType("int");

                    b.Property<string>("EnergyType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EngineType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("RentalPricePerDay")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("SeatNumber")
                        .HasColumnType("int");

                    b.Property<int?>("SellDate")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Available");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TransmissionType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Car");

                    b.HasKey("CarId")
                        .HasName("PK__Cars__68A0342EFCD139E9");

                    b.HasIndex(new[] { "BaseLocationId" }, "IX_Cars_BaseLocationId");

                    b.HasIndex(new[] { "CategoryId" }, "IX_Cars_CategoryId");

                    b.HasIndex(new[] { "EnergyType" }, "IX_Cars_EnergyType");

                    b.HasIndex(new[] { "RentalPricePerDay" }, "IX_Cars_RentalPricePerDay");

                    b.HasIndex(new[] { "SeatNumber" }, "IX_Cars_SeatNumber");

                    b.HasIndex(new[] { "TenantId" }, "IX_Cars_TenantId");

                    b.HasIndex(new[] { "TransmissionType" }, "IX_Cars_TransmissionType");

                    b.HasIndex(new[] { "TenantId", "LicensePlate" }, "UX_Cars_Tenant_LicensePlate")
                        .IsUnique();

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Car");

                    b.HasKey("CategoryId")
                        .HasName("PK__Categori__19093A0BDF788EA5");

                    b.HasIndex("ParentCategoryId");

                    b.HasIndex(new[] { "CategoryName" }, "UQ__Categori__8517B2E0F39EC167")
                        .IsUnique();

                    b.HasIndex(new[] { "VehicleType", "Slug" }, "UX_Categories_VT_Slug")
                        .IsUnique()
                        .HasFilter("([Slug] IS NOT NULL)");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.ChatMessage", b =>
                {
                    b.Property<long>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ChatMessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.HasKey("ChatMessageId");

                    b.HasIndex("SenderId");

                    b.HasIndex(new[] { "ConversationId" }, "IX_ChatMessages_ConversationId");

                    b.HasIndex(new[] { "SentAt" }, "IX_ChatMessages_SentAt");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsAnonymous")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId");

                    b.HasIndex(new[] { "BlogId" }, "IX_Comment_BlogId");

                    b.HasIndex(new[] { "UserId" }, "IX_Comment_UserId");

                    b.ToTable("Comment", (string)null);
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Project")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SubmittedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("ContactId")
                        .HasName("PK__Contact__5C66259B5FDEEF7E");

                    b.ToTable("Contact", (string)null);
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Conversation", b =>
                {
                    b.Property<int>("ConversationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConversationId"));

                    b.Property<DateTime?>("ClosedAt")
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastMessageAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(0)
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<int?>("StaffId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<int?>("TenantId")
                        .HasColumnType("int");

                    b.HasKey("ConversationId");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "CustomerId", "Status" }, "IX_Conversations_Customer_Status");

                    b.HasIndex(new[] { "LastMessageAt" }, "IX_Conversations_LastMessageAt");

                    b.HasIndex(new[] { "StaffId" }, "IX_Conversations_StaffId");

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.ConversationReadState", b =>
                {
                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<long>("LastReadMessageId")
                        .HasColumnType("bigint");

                    b.HasKey("ConversationId", "UserId")
                        .HasName("PK_ConversationReadState");

                    b.HasIndex(new[] { "UserId" }, "IX_CRS_User");

                    b.ToTable("ConversationReadStates");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<decimal?>("Lng")
                        .HasColumnType("decimal(9, 6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA497401B4413");

                    b.HasIndex("TenantId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.Property<int>("RecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RecordId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Cost")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MaintenanceDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("RecordId")
                        .HasName("PK__Maintena__FBDF78E9D1F84E3D");

                    b.HasIndex(new[] { "CarId" }, "IX_MaintenanceRecords_CarId");

                    b.ToTable("MaintenanceRecords");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("PaymentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ReservationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Unpaid");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("VnpTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payments__9B556A3856F28699");

                    b.HasIndex(new[] { "ReservationId" }, "IX_Payments_ReservationId");

                    b.HasIndex(new[] { "TenantId" }, "IX_Payments_TenantId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Promotion", b =>
                {
                    b.Property<int>("PromotionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromotionId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DiscountPercent")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.HasKey("PromotionId")
                        .HasName("PK__Promotio__52C42FCFDB38B80D");

                    b.HasIndex(new[] { "Code" }, "UQ__Promotio__A25C5AA7537857ED")
                        .IsUnique();

                    b.ToTable("Promotions");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Invalidated")
                        .HasColumnType("bit");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Used")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int?>("DropoffLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FromCity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<int?>("PickupLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReservationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<string>("ToCity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReservationId")
                        .HasName("PK__Reservat__B7EE5F24B88A996B");

                    b.HasIndex(new[] { "CarId" }, "IX_Reservations_CarId");

                    b.HasIndex(new[] { "DropoffLocationId" }, "IX_Reservations_Dropoff");

                    b.HasIndex(new[] { "PickupLocationId" }, "IX_Reservations_Pickup");

                    b.HasIndex(new[] { "TenantId" }, "IX_Reservations_TenantId");

                    b.HasIndex(new[] { "UserId" }, "IX_Reservations_UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReviewId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ReviewDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ReviewId")
                        .HasName("PK__Reviews__74BC79CE5D90B607");

                    b.HasIndex("TenantId");

                    b.HasIndex(new[] { "CarId" }, "IX_Reviews_CarId");

                    b.HasIndex(new[] { "UserId" }, "IX_Reviews_UserId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE1ADB3C0800");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Tenant", b =>
                {
                    b.Property<int>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TenantId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<byte>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)1);

                    b.HasKey("TenantId")
                        .HasName("PK__Tenants__2E9B47E1180B7A1C");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.TenantCategory", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("DisplayNameOverride")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.Property<int?>("SortOrderOverride")
                        .HasColumnType("int");

                    b.HasKey("TenantId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("TenantCategories");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.TenantMembership", b =>
                {
                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("(sysutcdatetime())");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TenantId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("TenantMemberships");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime?>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C90EA71FB");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Username" }, "UQ__Users__536C85E48F8E5FC4")
                        .IsUnique();

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D10534479BCCE5")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.UserBranch", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("TenantId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "TenantId", "LocationId");

                    b.HasIndex("LocationId");

                    b.HasIndex("TenantId");

                    b.ToTable("UserBranches");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.UserConversationVisibility", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("ConversationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsHidden")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "ConversationId");

                    b.HasIndex("ConversationId");

                    b.ToTable("UserConversationVisibilities");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Blog", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.User", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("FK__Blog__AuthorId__628FA481");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Car", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Location", "BaseLocation")
                        .WithMany("Cars")
                        .HasForeignKey("BaseLocationId")
                        .IsRequired();

                    b.HasOne("NewCarRental.Domain.Entities.Category", "Category")
                        .WithMany("Cars")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK__Cars__CategoryId__412EB0B6");

                    b.HasOne("NewCarRental.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Cars")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Cars_Tenants");

                    b.Navigation("BaseLocation");

                    b.Navigation("Category");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Category", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Category", "ParentCategory")
                        .WithMany("InverseParentCategory")
                        .HasForeignKey("ParentCategoryId")
                        .HasConstraintName("FK_Categories_Parent");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.ChatMessage", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Conversation", "Conversation")
                        .WithMany("ChatMessages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessages_Conversation");

                    b.HasOne("NewCarRental.Domain.Entities.User", "Sender")
                        .WithMany("ChatMessages")
                        .HasForeignKey("SenderId")
                        .IsRequired()
                        .HasConstraintName("FK_ChatMessages_Sender");

                    b.Navigation("Conversation");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Comment", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Comment_User_UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Conversation", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.User", "Customer")
                        .WithMany("ConversationCustomers")
                        .HasForeignKey("CustomerId")
                        .IsRequired()
                        .HasConstraintName("FK_Conversations_Customer");

                    b.HasOne("NewCarRental.Domain.Entities.User", "Staff")
                        .WithMany("ConversationStaffs")
                        .HasForeignKey("StaffId")
                        .HasConstraintName("FK_Conversations_Staff");

                    b.HasOne("NewCarRental.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Conversations")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Conversations_Tenants");

                    b.Navigation("Customer");

                    b.Navigation("Staff");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.ConversationReadState", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Conversation", "Conversation")
                        .WithMany("ConversationReadStates")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CRS_Conv");

                    b.HasOne("NewCarRental.Domain.Entities.User", "User")
                        .WithMany("ConversationReadStates")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_CRS_User");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Location", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Locations")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Locations_Tenants");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.MaintenanceRecord", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Car", "Car")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("CarId")
                        .IsRequired()
                        .HasConstraintName("FK__Maintenan__CarId__534D60F1");

                    b.Navigation("Car");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Payment", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Reservation", "Reservation")
                        .WithMany("Payments")
                        .HasForeignKey("ReservationId")
                        .IsRequired()
                        .HasConstraintName("FK__Payments__Reserv__4CA06362");

                    b.HasOne("NewCarRental.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Payments")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Payments_Tenants");

                    b.Navigation("Reservation");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservati__CarId__46E78A0C");

                    b.HasOne("NewCarRental.Domain.Entities.Location", "DropoffLocation")
                        .WithMany("ReservationDropoffLocations")
                        .HasForeignKey("DropoffLocationId")
                        .HasConstraintName("FK_Reservations_Locations_Dropoff");

                    b.HasOne("NewCarRental.Domain.Entities.Location", "PickupLocation")
                        .WithMany("ReservationPickupLocations")
                        .HasForeignKey("PickupLocationId")
                        .HasConstraintName("FK_Reservations_Locations_Pickup");

                    b.HasOne("NewCarRental.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Reservations")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Reservations_Tenants");

                    b.HasOne("NewCarRental.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reservati__UserI__45F365D3");

                    b.Navigation("Car");

                    b.Navigation("DropoffLocation");

                    b.Navigation("PickupLocation");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Review", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Car", "Car")
                        .WithMany("Reviews")
                        .HasForeignKey("CarId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__CarId__571DF1D5");

                    b.HasOne("NewCarRental.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Reviews")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_Reviews_Tenants");

                    b.HasOne("NewCarRental.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Reviews__UserId__5812160E");

                    b.Navigation("Car");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.TenantCategory", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Category", "Category")
                        .WithMany("TenantCategories")
                        .HasForeignKey("CategoryId")
                        .IsRequired()
                        .HasConstraintName("FK_TenantCategories_Categories");

                    b.HasOne("NewCarRental.Domain.Entities.Tenant", "Tenant")
                        .WithMany("TenantCategories")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_TenantCategories_Tenants");

                    b.Navigation("Category");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.TenantMembership", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Tenant", "Tenant")
                        .WithMany("TenantMemberships")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_TenantMemberships_Tenants");

                    b.HasOne("NewCarRental.Domain.Entities.User", "User")
                        .WithMany("TenantMemberships")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_TenantMemberships_Users");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.User", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.UserBranch", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Location", "Location")
                        .WithMany("UserBranches")
                        .HasForeignKey("LocationId")
                        .IsRequired()
                        .HasConstraintName("FK_UserBranches_Locations");

                    b.HasOne("NewCarRental.Domain.Entities.Tenant", "Tenant")
                        .WithMany("UserBranches")
                        .HasForeignKey("TenantId")
                        .IsRequired()
                        .HasConstraintName("FK_UserBranches_Tenants");

                    b.HasOne("NewCarRental.Domain.Entities.User", "User")
                        .WithMany("UserBranches")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserBranches_Users");

                    b.Navigation("Location");

                    b.Navigation("Tenant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.UserConversationVisibility", b =>
                {
                    b.HasOne("NewCarRental.Domain.Entities.Conversation", "Conversation")
                        .WithMany("UserConversationVisibilities")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserConversationVisibilities_Conversations");

                    b.HasOne("NewCarRental.Domain.Entities.User", "User")
                        .WithMany("UserConversationVisibilities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_UserConversationVisibilities_Users");

                    b.Navigation("Conversation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Car", b =>
                {
                    b.Navigation("MaintenanceRecords");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Category", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("InverseParentCategory");

                    b.Navigation("TenantCategories");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Conversation", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ConversationReadStates");

                    b.Navigation("UserConversationVisibilities");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Location", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("ReservationDropoffLocations");

                    b.Navigation("ReservationPickupLocations");

                    b.Navigation("UserBranches");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Reservation", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Cars");

                    b.Navigation("Conversations");

                    b.Navigation("Locations");

                    b.Navigation("Payments");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");

                    b.Navigation("TenantCategories");

                    b.Navigation("TenantMemberships");

                    b.Navigation("UserBranches");
                });

            modelBuilder.Entity("NewCarRental.Domain.Entities.User", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("ChatMessages");

                    b.Navigation("Comments");

                    b.Navigation("ConversationCustomers");

                    b.Navigation("ConversationReadStates");

                    b.Navigation("ConversationStaffs");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");

                    b.Navigation("TenantMemberships");

                    b.Navigation("UserBranches");

                    b.Navigation("UserConversationVisibilities");
                });
#pragma warning restore 612, 618
        }
    }
}
